### ISSUE TITLE
It runs Firefox 60, whereas I believe Firefox 52 is needed

### ISSUE THREAD

**Issue by amcsi** [fgsch/docker-webex#4] opened 2018-07-03 15:52 UTC
#3 is an issue as well, but I tried running firefox having removed that `--lxc-conf` option, and it launches Firefox 60. I believe only Firefox up to version 52 supports Java.

**Comment by fgsch** [comment] 2018-07-04 09:17
Thanks for the report. I will fix this.

**Comment by fgsch** [comment] 2018-07-04 10:58
I've pushed a fix. 

Can you give it a try and let me know?

**Comment by Chi-teck** [comment] 2018-07-04 11:20
I can confirm it is running Firefox 52.9.0 (32-bit) now.

**Comment by fgsch** [comment] 2018-07-04 11:23
@Chi-teck thanks. Does that mean that WebEx works though? 😄

**Comment by Chi-teck** [comment] 2018-07-04 11:36
When the Firefox started it shows "crash page".
```
Gah. Your tab just crashed.
We can help you!

Choose Restore This Tab to reload page content.
Will you help us?

Crash reports help us diagnose problems and make Firefox better.
Report this tab
Send a crash report for the tab you are viewing

    Include page URL with this crash report

Report background tabs
Update preferences to automatically submit backlogged crash reports (and get fewer messages like this from us in the future)
```
It is not big deal to close this tab and start Webex.
But sharing screen is not working anymore.

Also sound is not supported.
"the audio device is inaccessible now"

**Comment by Chi-teck** [comment] 2018-07-04 11:36
Note that the issue with sound existed before this update.

**Comment by fgsch** [comment] 2018-07-04 11:44
Hmm, audio worked in the past, and so did screen sharing (but see #1).

I will need to check why is broken now. Unfortunately I don't have a Linux box handy and the VM is crashing on my mac so it might take some time.

Thanks for testing. Much appreciated.

**Comment by Chi-teck** [comment] 2018-07-04 11:49
Screen sharing works fine on FF 60 (commit:60aa1b4).

**Comment by amcsi** [comment] 2018-07-04 11:56
@Chi-teck how could screen sharing possibly work fine of FF 60 when that doesn't support Java which WebEx needs?

**Comment by Chi-teck** [comment] 2018-07-04 12:10
@amcsi I have not idea, but sharing screen worked. Can this be because it was for 32 bit platforms?
The exact FF version was 60.0.2 (32-bit).

**Comment by amcsi** [comment] 2018-07-04 14:17
In any case I can confirm that with FF 60 the Java thing didn't pop up (nor was Java justed in `about:plugins`), but on current (9b67674) with FF 52 it did pop up and I was able to join a meeting...

However when I clicked on the button for `Call Using Computer`, I got an error saying "The Audio Device is unaccessible now.".

(Unfortunately it didn't cross my mind to test screensharing, so I can't report on that)

**Comment by fgsch** [comment] 2018-07-13 11:40
Continuing this in #5.

**Closed as completed by fgsch** 2018-07-13 11:40 UTC
Labels: help wanted
